layout_spectrum: 1
typography_spectrum: 0.7116004
color:
  saturation: 0.5726112
  lightness: 0.2413354
  brandStrength: 0.9962406
  brandColors:
    - '#0F0F14'
    - '#A19D98'
  rhythmicContrast: 0.8333869
name: Isabella Ahlin
