title: Isabella Ahlin
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5726112
  brandStrength: 1
  lightness: 0.8383458
  brandColors:
    - '#0F0F15'
    - '#2F3843'
    - '#919191'
  rhythmicContrast: 0.8333869
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Isabella Ahlin
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1068743
layout_spectrum: 0.5300752
