analytics:
  twitter: null
  google: UA-64586168-2
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.5300752
title: Isabella Ahlin
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5726112
  brandStrength: 1
  rhythmicContrast: 0.8333869
  brandColors:
    - '#0F0F15'
    - '#2F3843'
    - '#919191'
  lightness: 0.4935553
purpose: []
favicon: null
name: Isabella Ahlin
typography_spectrum: 0.3549946
