collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5726112
  lightness: 0.2413354
  brandStrength: 1
  brandColors:
    - '#0F0F15'
    - '#2F3843'
    - '#919191'
  rhythmicContrast: 0.8333869
typography_spectrum: 0.7116004
layout_spectrum: 1
name: Isabella Ahlin
