title: Isabella Ahlin
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5726112
  lightness: 0
  brandStrength: 0
  brandColors:
    - '#A5A19B'
    - '#6F757F'
    - '#424B5C'
    - '#0E0E15'
  rhythmicContrast: 0.8333869
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-64586168-2
  facebook: null
favicon: null
name: Isabella Ahlin
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 1
layout_spectrum: 0.8437164
