name: Isabella Ahlin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7116004
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Isabella Ahlin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0F0F15'
    - '#2F3843'
    - '#919191'
  brandStrength: 1
  lightness: 0.2413354
  saturation: 0.5726112
  rhythmicContrast: 0.8333869
purpose: []
